name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # Pour afficher les annotations de tests dans l'UI GitHub
      checks: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven (run tests)
      run: mvn -B clean verify --file pom.xml

    - name: Report Test Results in GitHub UI
      uses: dorny/test-reporter@v1
      if: always() # Montre les résultats même si les tests échouent
      with:
        name: JUnit Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
